### ISSUE TITLE
Test fail

### ISSUE THREAD

**Issue by bander-saeed94** [udacity/nd1309-Project-6b-Example-Template#1]
1) Contract: SupplyChain
       Testing smart contract function harvestItem() that allows a farmer to harvest coffee:
     AssertionError: Error: Invalid item SKU: expected { Object (s, e, ...) } to equal 1

Other passed

**Comment by Dhuliang** [comment]
@bander-saeed94 
I use `resultBufferOne[0].toNumber()` solve it

**Comment by heraclixus** [comment]
is this one resolved? I tried your solution @bander-saeed94 , but then it says: `AssertionError: Error: Invalid item SKU: expected 0 to equal 1`

**Comment by bander-saeed94** [comment]
Is the function you are testing implemnted in the smart contract
@heraclixus

**Comment by bander-saeed94** [comment]
> is this one resolved? I tried your solution @bander-saeed94 , but then it says: `AssertionError: Error: Invalid item SKU: expected 0 to equal 1`

you need to implement:
// Define a function 'fetchItemBufferOne' that fetches the data
  function fetchItemBufferOne(uint _upc) public view returns 
  (
  uint    itemSKU,
  uint    itemUPC,
  address ownerID,
  address originFarmerID,
  string  originFarmName,
  string  originFarmInformation,
  string  originFarmLatitude,
  string  originFarmLongitude
  ) 
  {
  // Assign values to the 8 parameters
  
    
  return 
  (
  itemSKU,
  itemUPC,
  ownerID,
  originFarmerID,
  originFarmName,
  originFarmInformation,
  originFarmLatitude,
  originFarmLongitude
  );
  }

  // Define a function 'fetchItemBufferTwo' that fetches the data
  function fetchItemBufferTwo(uint _upc) public view returns 
  (
  uint    itemSKU,
  uint    itemUPC,
  uint    productID,
  string  productNotes,
  uint    productPrice,
  uint    itemState,
  address distributorID,
  address retailerID,
  address consumerID
  ) 
  {
    // Assign values to the 9 parameters
  
    
  return 
  (
  itemSKU,
  itemUPC,
  productID,
  productNotes,
  productPrice,
  itemState,
  distributorID,
  retailerID,
  consumerID
  );
  }

**Comment by jlfera** [comment]
@Dhuliang Im using your solution:

`assert.equal(resultBufferOne[0].toNumber(), sku, 'Error: Invalid item SKU')`

But the console continue with this error:

```
1) Contract: SupplyChain
     Testing smart contract function harvestItem() that allows a farmer to harvest coffee:

    AssertionError: Error: Invalid item SKU: expected 0 to equal 1
    + expected - actual

    -0
    +1

    at Context.it (TestSupplychain.js:74:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Thanks
